# -*- coding: utf-8 -*- #
# frozen_string_literal: true

module Rouge
  module Lexers
    class SQL < RegexLexer
      title "SQL"
      desc "Structured Query Language, for relational databases"
      tag 'sql'
      filenames '*.sql'
      mimetypes 'text/x-sql'

      def self.keywords
        @keywords ||= Set.new %w(
          ABORT
          ABS
          ABSOLUTE
          ACCESS
          ACTION
          ADA
          ADD
          ADMIN
          AFTER
          AGGREGATE
          ALIAS
          ALL
          ALLOCATE
          ALSO
          ALTER
          ALWAYS
          ANALYSE
          ANALYZE
          AND
          ANTI
          ANY
          ARE
          ARRAY
          AS
          ASC
          ASENSITIVE
          ASOF
          ASSERTION
          ASSIGNMENT
          ASYMMETRIC
          AT
          ATOMIC
          ATTACH
          ATTRIBUTE
          AUTHORIZATION
          AVG
          BACKWARD
          BEFORE
          BEGIN
          BETWEEN
          BIGINT
          BINARY
          BIT
          BIT_LENGTH
          BITVAR
          BOOLEAN
          BOTH
          BREADTH
          BY
          C
          CACHE
          CALL
          CALLED
          CARDINALITY
          CASCADE
          CASCADED
          CASE
          CAST
          CATALOG
          CATALOG_NAME
          CHAIN
          CHAR
          CHAR_LENGTH
          CHARACTER
          CHARACTER_LENGTH
          CHARACTER_SET_CATALOG
          CHARACTER_SET_NAME
          CHARACTER_SET_SCHEMA
          CHARACTERISTICS
          CHECK
          CHECKED
          CHECKPOINT
          CLASS
          CLASS_ORIGIN
          CLOB
          CLOSE
          CLUSTER
          COALESCE
          COALSECE
          COBOL
          COLLATE
          COLLATION
          COLLATION_CATALOG
          COLLATION_NAME
          COLLATION_SCHEMA
          COLUMN
          COLUMN_NAME
          COLUMNS
          COMMAND_FUNCTION
          COMMAND_FUNCTION_CODE
          COMMENT
          COMMENTS
          COMMIT
          COMMITTED
          COMPLETION
          COMPRESSION
          CONCURRENTLY
          CONDITION_NUMBER
          CONFIGURATION
          CONFLICT
          CONNECT
          CONNECTION
          CONNECTION_NAME
          CONSTRAINT
          CONSTRAINT_CATALOG
          CONSTRAINT_NAME
          CONSTRAINT_SCHEMA
          CONSTRAINTS
          CONSTRUCTOR
          CONTAINS
          CONTENT
          CONTINUE
          CONVERSION
          CONVERT
          COPY
          CORRESPONTING
          COST
          COUNT
          CREATE
          CREATEDB
          CREATEUSER
          CROSS
          CSV
          CUBE
          CURRENT
          CURRENT_DATE
          CURRENT_PATH
          CURRENT_ROLE
          CURRENT_TIME
          CURRENT_TIMESTAMP
          CURRENT_USER
          CURSOR
          CURSOR_NAME
          CYCLE
          DATA
          DATABASE
          DATETIME_INTERVAL_CODE
          DATETIME_INTERVAL_PRECISION
          DAY
          DAYS
          DEALLOCATE
          DEC
          DECIMAL
          DECLARE
          DEFAULT
          DEFAULTS
          DEFERRABLE
          DEFERRED
          DEFINED
          DEFINER
          DELETE
          DELIMITER
          DELIMITERS
          DEPENDS
          DEREF
          DESC
          DESCRIBE
          DESCRIPTOR
          DESTROY
          DESTRUCTOR
          DETACH
          DETERMINISTIC
          DIAGNOSTICS
          DICTIONARY
          DISABLE
          DISCARD
          DISCONNECT
          DISPATCH
          DISTINCT
          DO
          DOCUMENT
          DOMAIN
          DOUBLE
          DROP
          DYNAMIC
          DYNAMIC_FUNCTION
          DYNAMIC_FUNCTION_CODE
          EACH
          ELSE
          ENABLE
          ENCODING
          ENCRYPTED
          END
          END-EXEC
          ENUM
          EQUALS
          ESCAPE
          ESCEPTION
          EVENT
          EVERY
          EXCEPT
          EXCLUDE
          EXCLUDING
          EXCLUSIVE
          EXEC
          EXECUTE
          EXISTING
          EXISTS
          EXPLAIN
          EXPORT
          EXPORT_STATE
          EXTENSION
          EXTERNAL
          EXTRACT
          FALSE
          FAMILY
          FETCH
          FILTER
          FINAL
          FIRST
          FLOAT
          FOLLOWING
          FOR
          FORCE
          FOREIGN
          FORTRAN
          FORWARD
          FOUND
          FREE
          FREEZE
          FROM
          FULL
          FUNCTION
          FUNCTIONS
          G
          GENERAL
          GENERATED
          GET
          GLOB
          GLOBAL
          GO
          GOTO
          GRANT
          GRANTED
          GROUP
          GROUPING
          GROUPING_ID
          HANDLER
          HAVING
          HEADER
          HIERARCHY
          HOLD
          HOST
          HOUR
          HOURS
          IDENTITY
          IF
          IGNORE
          ILIKE
          IMMEDIATE
          IMMUTABLE
          IMPLEMENTATION
          IMPLICIT
          IMPORT
          IN
          INCLUDE
          INCLUDING
          INCREMENT
          INDEX
          INDEXES
          INDITCATOR
          INFIX
          INHERIT
          INHERITS
          INITIALIZE
          INITIALLY
          INLINE
          INNER
          INOUT
          INPUT
          INSENSITIVE
          INSERT
          INSTALL
          INSTANTIABLE
          INSTEAD
          INT
          INTEGER
          INTERSECT
          INTERVAL
          INTO
          INVOKER
          IS
          ISNULL
          ISOLATION
          ITERATE
          JOIN
          JSON
          KEY
          KEY_MEMBER
          KEY_TYPE
          LABEL
          LANCOMPILER
          LANGUAGE
          LARGE
          LAST
          LATERAL
          LEADING
          LEAKPROOF
          LEFT
          LENGTH
          LESS
          LEVEL
          LIKE
          LIMIT
          LISTEN
          LOAD
          LOCAL
          LOCALTIME
          LOCALTIMESTAMP
          LOCATION
          LOCATOR
          LOCK
          LOCKED
          LOGGED
          LOWER
          MACRO
          MAP
          MAPPING
          MATCH
          MATERIALIZED
          MAX
          MAXVALUE
          MESSAGE_LENGTH
          MESSAGE_OCTET_LENGTH
          MESSAGE_TEXT
          METHOD
          MICROSECOND
          MICROSECONDS
          MILLISECOND
          MILLISECONDS
          MIN
          MINUTE
          MINUTES
          MINVALUE
          MOD
          MODE
          MODIFIES
          MODIFY
          MONTH
          MONTHS
          MORE
          MOVE
          MUMPS
          NAME
          NAMES
          NATIONAL
          NATURAL
          NCHAR
          NCLOB
          NEW
          NEXT
          NO
          NOCREATEDB
          NOCREATEUSER
          NONE
          NOT
          NOTHING
          NOTIFY
          NOTNULL
          NOWAIT
          NULL
          NULLABLE
          NULLIF
          NULLS
          NUMERIC
          OBJECT
          OCTET_LENGTH
          OF
          OFF
          OFFSET
          OIDS
          OLD
          ON
          ONLY
          OPEN
          OPERATION
          OPERATOR
          OPTION
          OPTIONS
          OR
          ORDER
          ORDINALITY
          OUT
          OUTER
          OUTPUT
          OVER
          OVERLAPS
          OVERLAY
          OVERRIDING
          OWNED
          OWNER
          PAD
          PARALLEL
          PARAMATER_NAME
          PARAMATER_ORDINAL_POSITION
          PARAMATER_SPECIFIC_SCHEMA
          PARAMETER
          PARAMETER_MODE
          PARAMETER_SPECIFIC_CATALOG
          PARAMETER_SPECIFIC_NAME
          PARAMETERS
          PARSER
          PARTIAL
          PARTITION
          PASCAL
          PASSING
          PASSWORD
          PENDANT
          PERCENT
          PIVOT
          PIVOT_LONGER
          PIVOT_WIDER
          PLACING
          PLANS
          PLI
          POLICY
          POSITION
          POSITIONAL
          POSTFIX
          PRAGMA
          PRECEDING
          PRECISION
          PREFIX
          PREORDER
          PREPARE
          PREPARED
          PRESERVE
          PRIMARY
          PRIOR
          PRIVILEGES
          PROCEDURAL
          PROCEDURE
          PROGRAM
          PUBLIC
          PUBLICATION
          QUALIFY
          QUOTE
          RANGE
          READ
          READS
          REAL
          REASSIGN
          RECHECK
          RECURSIVE
          REF
          REFERENCES
          REFERENCING
          REFRESH
          REINDEX
          RELATIVE
          RELEASE
          RENAME
          REPEATABLE
          REPLACE
          REPLICA
          RESET
          RESPECT
          RESTART
          RESTRICT
          RESULT
          RETURN
          RETURNED_LENGTH
          RETURNED_OCTET_LENGTH
          RETURNED_SQLSTATE
          RETURNING
          RETURNS
          REVOKE
          RIGHT
          ROLE
          ROLLBACK
          ROLLUP
          ROUTINE
          ROUTINE_CATALOG
          ROUTINE_NAME
          ROUTINE_SCHEMA
          ROW
          ROW_COUNT
          ROWS
          RULE
          SAMPLE
          SAVE_POINT
          SAVEPOINT
          SCALE
          SCHEMA
          SCHEMA_NAME
          SCHEMAS
          SCOPE
          SCROLL
          SEARCH
          SECOND
          SECONDS
          SECURITY
          SELECT
          SELF
          SEMI
          SENSITIVE
          SEQUENCE
          SEQUENCES
          SERIALIZABLE
          SERVER
          SERVER_NAME
          SESSION
          SESSION_USER
          SET
          SETOF
          SETS
          SHARE
          SHOW
          SIMILAR
          SIMPLE
          SIZE
          SKIP
          SMALLINT
          SNAPSHOT
          SOME
          SOURCE
          SPACE
          SPECIFIC
          SPECIFIC_NAME
          SPECIFICTYPE
          SQL
          SQLCODE
          SQLERROR
          SQLEXCEPTION
          SQLSTATE
          SQLWARNINIG
          STABLE
          STANDALONE
          START
          STATE
          STATEMENT
          STATIC
          STATISTICS
          STDIN
          STDOUT
          STORAGE
          STORED
          STRICT
          STRIP
          STRUCT
          STRUCTURE
          STYPE
          SUBCLASS_ORIGIN
          SUBLIST
          SUBSCRIPTION
          SUBSTRING
          SUM
          SUMMARIZE
          SYMMETRIC
          SYSID
          SYSTEM
          SYSTEM_USER
          TABLE
          TABLE_NAME
          TABLES
          TABLESAMPLE
          TABLESPACE
          TEMP
          TEMPLATE
          TEMPORARY
          TERMINATE
          TEXT
          THAN
          THEN
          TIME
          TIMESTAMP
          TIMEZONE_HOUR
          TIMEZONE_MINUTE
          TO
          TOAST
          TRAILING
          TRANSACTION
          TRANSACTIONS_COMMITTED
          TRANSACTIONS_ROLLED_BACK
          TRANSATION
          TRANSATION_ACTIVE
          TRANSFORM
          TRANSFORMS
          TRANSLATE
          TRANSLATION
          TREAT
          TRIGGER
          TRIGGER_CATALOG
          TRIGGER_NAME
          TRIGGER_SCHEMA
          TRIM
          TRUE
          TRUNCATE
          TRUSTED
          TRY_CAST
          TYPE
          TYPES
          UNBOUNDED
          UNCOMMITTED
          UNDER
          UNENCRYPTED
          UNION
          UNIQUE
          UNKNOWN
          UNLISTEN
          UNLOGGED
          UNNAMED
          UNNEST
          UNPIVOT
          UNTIL
          UPDATE
          UPPER
          USAGE
          USE
          USER
          USER_DEFINED_TYPE_CATALOG
          USER_DEFINED_TYPE_NAME
          USER_DEFINED_TYPE_SCHEMA
          USING
          VACUUM
          VALID
          VALIDATE
          VALIDATOR
          VALUE
          VALUES
          VARCHAR
          VARIABLE
          VARIADIC
          VARYING
          VERBOSE
          VERSION
          VIEW
          VIEWS
          VIRTUAL
          VOLATILE
          WHEN
          WHENEVER
          WHERE
          WHITESPACE
          WINDOW
          WITH
          WITHIN
          WITHOUT
          WORK
          WRAPPER
          WRITE
          XML
          XMLATTRIBUTES
          XMLCONCAT
          XMLELEMENT
          XMLEXISTS
          XMLFOREST
          XMLNAMESPACES
          XMLPARSE
          XMLPI
          XMLROOT
          XMLSERIALIZE
          XMLTABLE
          YEAR
          YEARS
          YES
          ZONE
          AUTO_DETECT
          FORMAT
          PARQUET
          ZSTD
          FIELD_IDS
          READ_ONLY
          MEDIAN
      )
      end

      def self.keywords_type
        # sources:
        # https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
        # https://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-overview.html
        # https://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
        @keywords_type ||= Set.new(%w(
            ZEROFILL UNSIGNED SIGNED SERIAL BIT TINYINT BOOL BOOLEAN SMALLINT
            MEDIUMINT INT INTEGER BIGINT DECIMAL DEC NUMERIC FIXED FLOAT DOUBLE
            PRECISION REAL
            DATE DATETIME TIMESTAMP TIME YEAR
            NATIONAL CHAR CHARACTER NCHAR BYTE
            VARCHAR VARYING BINARY VARBINARY TINYBLOB TINYTEXT BLOB TEXT
            MEDIUMBLOB MEDIUMTEXT LONGBLOB LONGTEXT ENUM
        ))
      end

      state :root do
        rule %r/\s+/m, Text
        rule %r/--.*/, Comment::Single
        rule %r(/\*), Comment::Multiline, :multiline_comments
        rule %r/\d+/, Num::Integer
        rule %r/'/, Str::Single, :single_string
        # A double-quoted string refers to a database object in our default SQL
        # dialect, which is appropriate for e.g. PostgreSQL and DuckDB.
        rule %r/"/, Name::Variable, :double_string
        rule %r/`/, Name::Variable, :backtick

        rule %r/\w[\w\d]*/ do |m|
          if self.class.keywords_type.include? m[0].upcase
            token Name::Builtin
          elsif self.class.keywords.include? m[0].upcase
            token Keyword
          else
            token Name
          end
        end

        rule %r([+*/<>=~!@#%&|?^-]), Operator
        rule %r/[;:()\[\]\{\},.]/, Punctuation
      end

      state :multiline_comments do
        rule %r(/[*]), Comment::Multiline, :multiline_comments
        rule %r([*]/), Comment::Multiline, :pop!
        rule %r([^/*]+), Comment::Multiline
        rule %r([/*]), Comment::Multiline
      end

      state :backtick do
        rule %r/\\./, Str::Escape
        rule %r/``/, Str::Escape
        rule %r/`/, Name::Variable, :pop!
        rule %r/[^\\`]+/, Name::Variable
      end

      state :single_string do
        rule %r/\\./, Str::Escape
        rule %r/''/, Str::Escape
        rule %r/'/, Str::Single, :pop!
        rule %r/[^\\']+/, Str::Single
      end

      state :double_string do
        rule %r/\\./, Str::Escape
        rule %r/""/, Str::Escape
        rule %r/"/, Name::Variable, :pop!
        rule %r/[^\\"]+/, Name::Variable
      end
    end
  end
end
